### ISSUE TITLE
Run on Windows and KeyError: 'result'

### ISSUE THREAD

**Issue by MMB22-hash** [blavka/xComfortMQTT#1]
Hello,
Is there any chance to make it work on Windows envoriment?
I'm trying to control Xcomfort from Node-red via Mqtt.
Is there any hope?
Kind Regards.

**Comment by blavka** [comment]
It is possible,
only install Python3 for Win and pip, I found this instructions https://www.youtube.com/watch?v=MkfNTfdWI84
And then use this command:
pip install -U xComfortMQTT

**Comment by MMB22-hash** [comment]
Hello,
Thank you for your feedback.
I manage to installed via python but i'm stuck on "Insert this snippet to
the file /etc/xComfortMQTT.yml:"
No such file installed on my system (windows 7)

I found an *exe file xcomfortmqtt.exe in C:\msys64\mingw32\bin but when i
run it i get

C:\msys64\mingw32\bin>xcomfortmqtt
Usage: xComfortMQTT [OPTIONS]
Try 'xComfortMQTT --help' for help.

Error: Missing option '--config' / '-c'.

I believe it is not possible to run it on windows environment.
If you have different solution please let me know.
Regards,
Bogdan

**Comment by blavka** [comment]
Yes, etc folder is not present on windows, but You can create configuration file where you want. Content is in README or download example from repo https://raw.githubusercontent.com/blavka/xComfortMQTT/master/config.yml, and replace /etc/xComfortMQTT.yml the actual path to the configuration file. For example:
Create folder _conf_ on disk _C_ and download example _config.yml_ then comand for run will be:
_xComfortMQTT -c c:\conf\config.yml_

**Comment by MMB22-hash** [comment]
I'm stuck

C:\msys64\mingw32\bin>xcomfortmqtt -c C:\msys64\mingw32\bin\config.yml
2021-01-02 20:36:45,596 INFO: Process started
2021-01-02 20:36:45,601 INFO: SHC host: 192.168.1.3
2021-01-02 20:36:45,606 INFO: MQTT broker host: 192.168.1.2, port: 1883,
use tls
: False
2021-01-02 20:36:45,611 INFO: Connected to MQTT broker with code 0
'result'

.....

**Comment by blavka** [comment]
OK, 
please run with debug log and send me result

xcomfortmqtt -v DEBUG -c C:\msys64\mingw32\bin\config.yml

And tell me yout shc info 
my is Version software SM: Eaton-SHC-7.5-2.4.0

**Comment by MMB22-hash** [comment]
Software version :
Eaton-SHC-7.5-2.4.3


C:\msys64\mingw32\bin>xcomfortmqtt -v DEBUG -c
C:\msys64\mingw32\bin\config.yml
2021-01-02 20:56:22,600 INFO: Process started
2021-01-02 20:56:22,605 INFO: SHC host: 192.168.1.3
2021-01-02 20:56:22,610 INFO: MQTT broker host: 192.168.1.2, port: 1883,
use tls
: False
2021-01-02 20:56:22,610 DEBUG: Login to 192.168.1.3
2021-01-02 20:56:22,620 DEBUG: Starting new HTTP connection (1):
192.168.1.3:80
2021-01-02 20:56:22,620 INFO: Connected to MQTT broker with code 0
2021-01-02 20:56:22,625 DEBUG: Subscribe: xcomfort/+/+/value/set
2021-01-02 20:56:22,630 DEBUG: Subscribe: xcomfort/+/+/state/set
2021-01-02 20:56:22,630 DEBUG: Subscribe: xcomfort/+/+/+/get
2021-01-02 20:56:22,655 DEBUG: http://192.168.1.3:80 "POST
/system/http/login HT
TP/1.1" 302 175
2021-01-02 20:56:22,875 DEBUG: http://192.168.1.3:80 "GET / HTTP/1.1" 302 0
2021-01-02 20:56:22,900 DEBUG: http://192.168.1.3:80 "GET /system/console
HTTP/1
.1" 302 217
2021-01-02 20:56:23,212 DEBUG: http://192.168.1.3:80 "GET
/system/console/System
 HTTP/1.1" 200 None
2021-01-02 20:56:23,897 DEBUG: http://192.168.1.3:80 "POST /remote/json-rpc
HTTP
/1.1" 200 None
2021-01-02 20:56:24,222 DEBUG: http://192.168.1.3:80 "POST /remote/json-rpc
HTTP
/1.1" 200 None
2021-01-02 20:56:24,497 DEBUG: http://192.168.1.3:80 "POST /remote/json-rpc
HTTP
/1.1" 200 None
2021-01-02 20:56:24,782 DEBUG: http://192.168.1.3:80 "POST /remote/json-rpc
HTTP
/1.1" 200 None
2021-01-02 20:56:25,187 DEBUG: http://192.168.1.3:80 "POST /remote/json-rpc
HTTP
/1.1" 200 None
2021-01-02 20:56:25,472 DEBUG: http://192.168.1.3:80 "POST /remote/json-rpc
HTTP
/1.1" 200 None
2021-01-02 20:56:25,747 DEBUG: http://192.168.1.3:80 "POST /remote/json-rpc
HTTP
/1.1" 200 None
2021-01-02 20:56:26,047 DEBUG: http://192.168.1.3:80 "POST /remote/json-rpc
HTTP
/1.1" 200 None
2021-01-02 20:56:26,357 DEBUG: http://192.168.1.3:80 "POST /remote/json-rpc
HTTP
/1.1" 200 None
2021-01-02 20:56:26,899 DEBUG: http://192.168.1.3:80 "POST /remote/json-rpc
HTTP
/1.1" 200 None
2021-01-02 20:56:27,189 DEBUG: http://192.168.1.3:80 "POST /remote/json-rpc
HTTP
/1.1" 200 None
2021-01-02 20:56:27,574 DEBUG: http://192.168.1.3:80 "POST /remote/json-rpc
HTTP
/1.1" 200 None
2021-01-02 20:56:27,809 DEBUG: http://192.168.1.3:80 "POST /remote/json-rpc
HTTP
/1.1" 200 None
'result'
Traceback (most recent call last):
  File "C:\msys64\mingw32\lib\python3.8\runpy.py", line 194, in
_run_module_as_m
ain
    return _run_code(code, main_globals, None,
  File "C:\msys64\mingw32\lib\python3.8\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\msys64\mingw32\bin\xComfortMQTT.exe\__main__.py", line 7, in
<module>

  File
"C:\msys64\mingw32\lib\python3.8\site-packages\xComfortMQTT\__init__.py",
 line 38, in main
    raise e
  File
"C:\msys64\mingw32\lib\python3.8\site-packages\xComfortMQTT\__init__.py",
 line 32, in main
    cli()
  File "C:\msys64\mingw32\lib\python3.8\site-packages\click\core.py", line
829,
in __call__
    return self.main(*args, **kwargs)
  File "C:\msys64\mingw32\lib\python3.8\site-packages\click\core.py", line
782,
in main
    rv = self.invoke(ctx)
  File "C:\msys64\mingw32\lib\python3.8\site-packages\click\core.py", line
1066,
 in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\msys64\mingw32\lib\python3.8\site-packages\click\core.py", line
610,
in invoke
    return callback(*args, **kwargs)
  File
"C:\msys64\mingw32\lib\python3.8\site-packages\xComfortMQTT\__init__.py",
 line 22, in cli
    service.start()
  File
"C:\msys64\mingw32\lib\python3.8\site-packages\xComfortMQTT\xComforMqtt.p
y", line 133, in start
    self._zones_load()
  File
"C:\msys64\mingw32\lib\python3.8\site-packages\xComfortMQTT\xComforMqtt.p
y", line 164, in _zones_load
    zone_devices = self._shc.get_devices(zone['zoneId'])
  File
"C:\msys64\mingw32\lib\python3.8\site-packages\xComfortMQTT\shc_client.py
", line 83, in get_devices
    return self.rpc("StatusControlFunction/getDevices", [zoneId, ""])
  File
"C:\msys64\mingw32\lib\python3.8\site-packages\xComfortMQTT\shc_client.py
", line 63, in rpc
    return response.json()['result']
KeyError: 'result'

**Comment by blavka** [comment]
Ok,
I update my SHC to Eaton-SHC-7.5-2.4.3 and add more debug messages for fix.

**Comment by blavka** [comment]
I published a new version v1.1.2 with a fix.

**Comment by MMB22-hash** [comment]
Installed and still not working, Debug :

2021-01-03 20:54:32,784 DEBUG: http://192.168.1.3:80 "GET
/system/console/System
 HTTP/1.1" 200 None
2021-01-03 20:54:33,489 DEBUG: http://192.168.1.3:80 "POST /remote/json-rpc
HTTP
/1.1" 200 None
2021-01-03 20:54:33,694 DEBUG: Response: {'id': 1, 'result': [{'virtual':
False,
 'mainIndoorTemperature': False, 'zoneName': 'Living', 'zoneId': 'hz_1'},
{'virt
ual': False, 'mainIndoorTemperature': False, 'zoneName': 'Camera Tehnica',
'zone
Id': 'hz_2'}, {'virtual': False, 'mainIndoorTemperature': False,
'zoneName': 'Do
rmitor 1', 'zoneId': 'hz_3'}, {'virtual': False, 'mainIndoorTemperature':
False,
 'zoneName': 'Dormitor 2', 'zoneId': 'hz_4'}, {'virtual': False,
'mainIndoorTemp
erature': False, 'zoneName': 'Baie 1', 'zoneId': 'hz_5'}, {'virtual':
False, 'ma
inIndoorTemperature': False, 'zoneName': 'Baie 2', 'zoneId': 'hz_6'},
{'virtual'
: False, 'mainIndoorTemperature': True, 'zoneName': 'Hol', 'zoneId':
'hz_7'}, {'
virtual': False, 'mainIndoorTemperature': False, 'zoneName': 'Bucatarie',
'zoneI
d': 'hz_8'}, {'virtual': False, 'mainIndoorTemperature': False, 'zoneName':
'Int
erior', 'zoneId': 'hz_9'}, {'virtual': False, 'mainIndoorTemperature':
False, 'z
oneName': 'Camara', 'zoneId': 'hz_10'}, {'virtual': False,
'mainIndoorTemperatur
e': False, 'zoneName': 'Exterior', 'zoneId': 'hz_11'}, {'virtual': True,
'zoneNa
me': 'Camera Overview', 'zoneId': 'hz_camera_overview'}], 'jsonrpc': '2.0'}
2021-01-03 20:54:33,724 DEBUG: Load device for zone "hz_1" param:
{'virtual': Fa
lse, 'mainIndoorTemperature': False, 'zoneName': 'Living', 'zoneId': 'hz_1'}
2021-01-03 20:54:33,866 DEBUG: http://192.168.1.3:80 "POST /remote/json-rpc
HTTP
/1.1" 200 None
2021-01-03 20:54:34,066 DEBUG: Response: {'id': 2, 'result': [{'id':
'xCo:442401
3_u0', 'unit': '%', 'name': 'Spot Living ', 'value': '0', 'operations':
['value'
], 'type': 'DimActuator'}, {'id': 'xCo:4422775_u0', 'unit': '', 'name':
'Lustra
Living ', 'value': 'OFF', 'operations': ['off', 'on', 'toggle'], 'type':
'LightA
ctuator'}, {'id': 'xCo:4910835_u0', 'unit': '', 'name': 'Rulou Usa Terasa
', 'va
lue': 'CLOSED', 'operations': ['open', 'close', 'stop', 'stepOpen',
'stepClose']
, 'type': 'ShutterActuator'}, {'id': 'xCo:4910865_u0', 'unit': '', 'name':
'Rulo
u Geam Living ', 'value': 'CLOSED', 'operations': ['open', 'close', 'stop',
'ste
pOpen', 'stepClose'], 'type': 'ShutterActuator'}, {'id': 'xCo:4067884_u1',
'unit
': '%', 'name': 'Air Quality', 'value': '96', 'operations': ['history'],
'type':
 'AirQualitySensor'}, {'id': 'xCo:4949156_u1', 'unit': '', 'name': 'Usa
Living',
 'value': 'CLOSED', 'type': 'BinaryDoorSensor'}, {'id': 'xCo:4949156_u0',
'unit'
: '', 'name': 'Geam Living', 'value': 'CLOSED', 'type':
'BinaryWindowSensor'}, {
'id': 'xCo:4772291_u0', 'unit': '°C', 'name': 'Temperatura Living P1',
'value':
'24.2', 'operations': ['history'], 'type': 'TemperatureSensor'}, {'id':
'xCo:477
2291_u1', 'unit': '°C', 'name': 'Temperatura Living P2', 'value': '25.3',
'opera
tions': ['history'], 'type': 'TemperatureSensor'}], 'jsonrpc': '2.0'}
2021-01-03 20:54:34,096 DEBUG: Load device for zone "hz_2" param:
{'virtual': Fa
lse, 'mainIndoorTemperature': False, 'zoneName': 'Camera Tehnica',
'zoneId': 'hz
_2'}
2021-01-03 20:54:34,186 DEBUG: http://192.168.1.3:80 "POST /remote/json-rpc
HTTP
/1.1" 200 None
2021-01-03 20:54:34,386 DEBUG: Response: {'id': 3, 'result': [{'id':
'xCo:469361
9_u0', 'unit': '', 'name': 'Iluminat CT ', 'value': 'OFF', 'operations':
['off',
 'on', 'toggle'], 'type': 'LightActuator'}, {'id': 'xCo:4530504_u1',
'unit': '',
 'name': 'Usa camera tehnica', 'value': '?', 'type': 'BinaryDoorSensor'},
{'id':
 'xCo:4542126_u0', 'unit': '', 'name': 'Senzor miscare CT', 'value':
'MOTION', '
type': 'BinaryMotionSensor'}, {'id': 'xCo:4576324_u1', 'unit': '°C',
'name': 'Te
mperatura Camera tehnica', 'value': '22.1', 'operations': ['history'],
'type': '
TemperatureSensor'}], 'jsonrpc': '2.0'}
2021-01-03 20:54:34,401 DEBUG: Load device for zone "hz_3" param:
{'virtual': Fa
lse, 'mainIndoorTemperature': False, 'zoneName': 'Dormitor 1', 'zoneId':
'hz_3'}

2021-01-03 20:54:34,486 DEBUG: http://192.168.1.3:80 "POST /remote/json-rpc
HTTP
/1.1" 200 None
2021-01-03 20:54:34,686 DEBUG: Response: {'id': 4, 'result': [{'id':
'xCo:469464
3_u0', 'unit': '%', 'name': 'Spot Dormitor1 ', 'value': '0', 'operations':
['val
ue'], 'type': 'DimActuator'}, {'id': 'xCo:4793318_u0', 'unit': '', 'name':
'Rulo
u Dormitor1 ', 'value': 'CLOSED', 'operations': ['open', 'close', 'stop',
'stepO
pen', 'stepClose'], 'type': 'ShutterActuator'}, {'id': 'xCo:4949165_u0',
'unit':
 '', 'name': 'Geam Dormitor 1', 'value': 'CLOSED', 'type':
'BinaryWindowSensor'}
, {'id': 'xCo:4778062_u0', 'unit': '°C', 'name': 'Temperatura Dormitor 1',
'valu
e': '28.5', 'operations': ['history'], 'type': 'TemperatureSensor'}],
'jsonrpc':
 '2.0'}
2021-01-03 20:54:34,701 DEBUG: Load device for zone "hz_4" param:
{'virtual': Fa
lse, 'mainIndoorTemperature': False, 'zoneName': 'Dormitor 2', 'zoneId':
'hz_4'}

2021-01-03 20:54:34,821 DEBUG: http://192.168.1.3:80 "POST /remote/json-rpc
HTTP
/1.1" 200 None
2021-01-03 20:54:35,066 DEBUG: Response: {'id': 5, 'result': [{'id':
'xCo:441891
4_u0', 'unit': '%', 'name': 'Spot Dormitor2 ', 'value': '98', 'operations':
['va
lue'], 'type': 'DimActuator'}, {'id': 'xCo:4417831_u0', 'unit': '', 'name':
'Ilu
minat Dressing ', 'value': 'OFF', 'operations': ['off', 'on', 'toggle'],
'type':
 'LightActuator'}, {'id': 'xCo:4558743_u0', 'unit': '', 'name': 'Iluminat
D2 Pat
 Dreapta ', 'value': 'OFF', 'operations': ['off', 'on', 'toggle'], 'type':
'Ligh
tActuator'}, {'id': 'xCo:4559323_u0', 'unit': '', 'name': 'Iluminat D2 Pat
Stang
a ', 'value': 'OFF', 'operations': ['off', 'on', 'toggle'], 'type':
'LightActuat
or'}, {'id': 'xCo:4793315_u0', 'unit': '', 'name': 'Rulou Geam Mare D2 ',
'value
': 'CLOSED', 'operations': ['open', 'close', 'stop', 'stepOpen',
'stepClose'], '
type': 'ShutterActuator'}, {'id': 'xCo:4793321_u0', 'unit': '', 'name':
'Rulou G
eam Mic D2 ', 'value': 'CLOSED', 'operations': ['open', 'close', 'stop',
'stepOp
en', 'stepClose'], 'type': 'ShutterActuator'}, {'id': 'xCo:4420204_u0',
'unit':
'', 'name': 'Geam D2+B2  (Channel A)', 'value': '?', 'type':
'BinaryWindowSensor
'}, {'id': 'xCo:4778065_u0', 'unit': '°C', 'name': 'Temperatura Dormitor
2', 'va
lue': '29', 'operations': ['history'], 'type': 'TemperatureSensor'}],
'jsonrpc':
 '2.0'}
2021-01-03 20:54:35,091 DEBUG: Load device for zone "hz_5" param:
{'virtual': Fa
lse, 'mainIndoorTemperature': False, 'zoneName': 'Baie 1', 'zoneId': 'hz_5'}
2021-01-03 20:54:35,171 DEBUG: http://192.168.1.3:80 "POST /remote/json-rpc
HTTP
/1.1" 200 None
2021-01-03 20:54:35,466 DEBUG: Response: {'id': 6, 'result': [{'id':
'xCo:462807
0_u0', 'unit': '', 'name': 'Iluminat Baie 1 ', 'value': 'OFF',
'operations': ['o
ff', 'on', 'toggle'], 'type': 'LightActuator'}, {'id': 'xCo:4628065_u0',
'unit':
 '', 'name': 'Ventilatie Baie1 ', 'value': 'OFF', 'operations': ['off',
'on', 't
oggle'], 'type': 'SwitchActuator'}, {'id': 'xCo:4530504_u0', 'unit': '',
'name':
 'Geam Baie 1', 'value': '?', 'type': 'BinaryWindowSensor'}, {'id':
'xCo:4576324
_u0', 'unit': '°C', 'name': 'Temperatura Baie 1', 'value': '22.1',
'operations':
 ['history'], 'type': 'TemperatureSensor'}], 'jsonrpc': '2.0'}
2021-01-03 20:54:35,481 DEBUG: Load device for zone "hz_6" param:
{'virtual': Fa
lse, 'mainIndoorTemperature': False, 'zoneName': 'Baie 2', 'zoneId': 'hz_6'}
2021-01-03 20:54:35,561 DEBUG: http://192.168.1.3:80 "POST /remote/json-rpc
HTTP
/1.1" 200 None
2021-01-03 20:54:35,766 DEBUG: Response: {'id': 7, 'result': [{'id':
'xCo:477796
4_u0', 'unit': '', 'name': 'Iluminat Baie 2 ', 'value': 'OFF',
'operations': ['o
ff', 'on', 'toggle'], 'type': 'LightActuator'}, {'id': 'xCo:4563058_u0',
'unit':
 '', 'name': 'Ventilatie Baie2 ', 'value': 'OFF', 'operations': ['off',
'on', 't
oggle'], 'type': 'SwitchActuator'}, {'id': 'xCo:4420204_u1', 'unit': '',
'name':
 'Geam Baie 2', 'value': 'OPENED', 'type': 'BinaryWindowSensor'}, {'id':
'xCo:47
78065_u1', 'unit': '°C', 'name': 'Temperatura Baie 2', 'value': '24.6',
'operati
ons': ['history'], 'type': 'TemperatureSensor'}], 'jsonrpc': '2.0'}
2021-01-03 20:54:35,783 DEBUG: Load device for zone "hz_7" param:
{'virtual': Fa
lse, 'mainIndoorTemperature': True, 'zoneName': 'Hol', 'zoneId': 'hz_7'}
2021-01-03 20:54:35,863 DEBUG: http://192.168.1.3:80 "POST /remote/json-rpc
HTTP
/1.1" 200 None
2021-01-03 20:54:36,130 DEBUG: Response: {'id': 8, 'result': [{'id':
'xCo:469460
0_u0', 'unit': '%', 'name': 'Spot Hol Mare', 'value': '20', 'operations':
['valu
e'], 'type': 'DimActuator'}, {'id': 'xCo:4694602_u0', 'unit': '%', 'name':
'Spot
 Hol mic ', 'value': '100', 'operations': ['value'], 'type':
'DimActuator'}, {'i
d': 'xCo:4949165_u1', 'unit': '', 'name': 'Usa principala', 'value':
'OPENED', '
type': 'BinaryDoorSensor'}, {'id': 'xCo:4908020_u0', 'unit': '°C', 'name':
'Temp
eratura Hol', 'value': '22.5', 'operations': ['history'], 'type':
'TemperatureSe
nsor'}], 'jsonrpc': '2.0'}
2021-01-03 20:54:36,145 DEBUG: Load device for zone "hz_8" param:
{'virtual': Fa
lse, 'mainIndoorTemperature': False, 'zoneName': 'Bucatarie', 'zoneId':
'hz_8'}
2021-01-03 20:54:36,255 DEBUG: http://192.168.1.3:80 "POST /remote/json-rpc
HTTP
/1.1" 200 None
2021-01-03 20:54:36,450 DEBUG: Response: {'id': 9, 'result': [{'id':
'xCo:450843
0_u0', 'unit': '', 'name': 'Spot Bucatarie ', 'value': 'ON', 'operations':
['off
', 'on', 'toggle'], 'type': 'LightActuator'}, {'id': 'xCo:4560566_u0',
'unit': '
', 'name': 'Banda blat lung ', 'value': 'ON', 'operations': ['off', 'on',
'toggl
e'], 'type': 'LightActuator'}, {'id': 'xCo:4693530_u0', 'unit': '', 'name':
'Ban
da led aragaz ', 'value': 'ON', 'operations': ['off', 'on', 'toggle'],
'type': '
LightActuator'}, {'id': 'xCo:4693568_u0', 'unit': '', 'name': 'Lustra
Bucatarie
', 'value': 'ON', 'operations': ['off', 'on', 'toggle'], 'type':
'LightActuator'
}, {'id': 'xCo:4785772_u0', 'unit': '', 'name': 'Rulou Geam Mare Bucatarie
', 'v
alue': 'CLOSED', 'operations': ['open', 'close', 'stop', 'stepOpen',
'stepClose'
], 'type': 'ShutterActuator'}, {'id': 'xCo:4793314_u0', 'unit': '', 'name':
'Rul
ou Geam Mic Bucatarie ', 'value': 'CLOSED', 'operations': ['open', 'close',
'sto
p', 'stepOpen', 'stepClose'], 'type': 'ShutterActuator'}, {'id':
'xCo:4949167_u0
', 'unit': '', 'name': 'Geam mic Bucatarie', 'value': 'CLOSED', 'type':
'BinaryW
indowSensor'}, {'id': 'xCo:4908020_u1', 'unit': '°C', 'name': 'Temperatura
Bucat
arie', 'value': '26.4', 'operations': ['history'], 'type':
'TemperatureSensor'}]
, 'jsonrpc': '2.0'}
2021-01-03 20:54:36,480 DEBUG: Load device for zone "hz_9" param:
{'virtual': Fa
lse, 'mainIndoorTemperature': False, 'zoneName': 'Interior', 'zoneId':
'hz_9'}
2021-01-03 20:54:36,785 DEBUG: http://192.168.1.3:80 "POST /remote/json-rpc
HTTP
/1.1" 200 None
2021-01-03 20:54:36,985 DEBUG: Response: {'id': 10, 'result': [{'id':
'xCo:45584
84_u0', 'unit': '', 'name': 'Armare Alarma ', 'value': 'OFF', 'display':
True, '
operations': ['off', 'on', 'toggle'], 'type': 'SwitchActuator',
'sequenceNumber'
: 0}, {'id': 'xCo:4563082_u0', 'unit': '', 'name': 'PIR SUM ', 'value':
'OFF', '
display': True, 'operations': ['off', 'on', 'toggle'], 'type':
'SwitchActuator',
 'sequenceNumber': 1}, {'id': 'xCo:4628057_u0', 'unit': '', 'name': 'Home
Manage
r Connect ', 'value': 'OFF', 'display': True, 'operations': ['off', 'on',
'toggl
e'], 'type': 'SwitchActuator', 'sequenceNumber': 2}, {'id':
'xCo:4067884_u1', 'u
nit': '%', 'name': 'Air Quality', 'value': '96', 'display': True,
'operations':
['history'], 'type': 'AirQualitySensor', 'sequenceNumber': 3}, {'id':
'xCo:45779
90_u0', 'unit': '', 'name': 'Prezenta tensiune retea', 'value': 'ON',
'display':
 True, 'type': 'BinaryInput', 'sequenceNumber': 4}, {'id':
'xCo:6375894_u2', 'un
it': 'A', 'name': 'Main House L1 Phase  Current ', 'value': '5.8',
'display': Tr
ue, 'type': 'CurrentMeter', 'sequenceNumber': 5}, {'id': 'xCo:6375896_u2',
'unit
': 'A', 'name': 'Main House L2 Phase  Current ', 'value': '1.7', 'display':
True
, 'type': 'CurrentMeter', 'sequenceNumber': 6}, {'id': 'xCo:6375895_u2',
'unit':
 'A', 'name': 'Main House L3 Phase  Current ', 'value': '2.2', 'display':
True,
'type': 'CurrentMeter', 'sequenceNumber': 7}, {'id': 'xCo:6375894_u0',
'unit': '
kWh', 'name': 'Main House L1 Phase  Energy', 'value': '9453.4', 'display':
True,
 'operations': ['history'], 'type': 'MainEnergyConsumptionMeter',
'sequenceNumbe
r': 8}, {'id': 'xCo:6375896_u0', 'unit': 'kWh', 'name': 'Main House L2
Phase  En
ergy', 'value': '11385', 'display': True, 'operations': ['history'],
'type': 'Ma
inEnergyConsumptionMeter', 'sequenceNumber': 9}, {'id': 'xCo:6375895_u0',
'unit'
: 'kWh', 'name': 'Main House L3 Phase  Energy', 'value': '24343.4',
'display': T
rue, 'operations': ['history'], 'type': 'MainEnergyConsumptionMeter',
'sequenceN
umber': 10}, {'id': 'xCo:6375894_u1', 'unit': 'W', 'name': 'Main House L1
Phase
 Power ', 'value': '0', 'display': True, 'type':
'MainPowerConsumptionMeter', 's
equenceNumber': 11}, {'id': 'xCo:6375896_u1', 'unit': 'W', 'name': 'Main
House L
2 Phase  Power ', 'value': '0', 'display': True, 'type':
'MainPowerConsumptionMe
ter', 'sequenceNumber': 12}, {'id': 'xCo:6375895_u1', 'unit': 'W', 'name':
'Main
 House L3 Phase  Power ', 'value': '0', 'display': True, 'type':
'MainPowerConsu
mptionMeter', 'sequenceNumber': 13}, {'id': 'xCo:6375894_u3', 'unit': 'V',
'name
': 'Main House L1 Phase  Voltage ', 'value': '231.1', 'display': True,
'type': '
VoltageMeter', 'sequenceNumber': 14}, {'id': 'xCo:6375896_u3', 'unit': 'V',
'nam
e': 'Main House L2 Phase  Voltage ', 'value': '234.5', 'display': True,
'type':
'VoltageMeter', 'sequenceNumber': 15}, {'id': 'xCo:6375895_u3', 'unit':
'V', 'na
me': 'Main House L3 Phase  Voltage ', 'value': '234.1', 'display': True,
'type':
 'VoltageMeter', 'sequenceNumber': 16}, {'id': 'xCo:4619464_u1', 'unit':
'', 'na
me': 'Incendiu', 'value': '?', 'display': True, 'type':
'BinarySmokeSensor', 'se
quenceNumber': 17}, {'id': 'xCo:4554279_u1', 'unit': '', 'name': 'PIR
Magazie',
'value': 'OFF', 'display': True, 'type': 'BinaryInput', 'sequenceNumber':
18}, {
'id': 'xCo:4422803_u0', 'unit': '', 'name': 'Ventilatie casa ON/OFF ',
'value':
'OFF', 'display': True, 'operations': ['off', 'on', 'toggle'], 'type':
'SwitchAc
tuator', 'sequenceNumber': 19}], 'jsonrpc': '2.0'}
2021-01-03 20:54:37,103 DEBUG: Load device for zone "hz_10" param:
{'virtual': F
alse, 'mainIndoorTemperature': False, 'zoneName': 'Camara', 'zoneId':
'hz_10'}
2021-01-03 20:54:37,217 DEBUG: http://192.168.1.3:80 "POST /remote/json-rpc
HTTP
/1.1" 200 None
2021-01-03 20:54:37,437 DEBUG: Response: {'id': 11, 'result': [{'id':
'xCo:45084
03_u0', 'unit': '', 'name': 'Iluminat camara ', 'value': 'OFF',
'operations': ['
off', 'on', 'toggle'], 'type': 'LightActuator'}, {'id': 'xCo:4949167_u1',
'unit'
: '', 'name': 'Usa Camara', 'value': 'CLOSED', 'type': 'BinaryDoorSensor'},
{'id
': 'xCo:4619464_u0', 'unit': '', 'name': 'Geam Camara', 'value': '?',
'type': 'B
inaryWindowSensor'}, {'id': 'xCo:4576336_u0', 'unit': '°C', 'name':
'Temperatura
 Camara', 'value': '24.2', 'operations': ['history'], 'type':
'TemperatureSensor
'}], 'jsonrpc': '2.0'}
2021-01-03 20:54:37,452 DEBUG: Load device for zone "hz_11" param:
{'virtual': F
alse, 'mainIndoorTemperature': False, 'zoneName': 'Exterior', 'zoneId':
'hz_11'}

2021-01-03 20:54:37,617 DEBUG: http://192.168.1.3:80 "POST /remote/json-rpc
HTTP
/1.1" 200 None
2021-01-03 20:54:37,842 DEBUG: Response: {'id': 12, 'result': [{'id':
'xCo:46280
59_u0', 'unit': '', 'name': 'Iluminat polata camara ', 'value': 'ON',
'display':
 True, 'operations': ['off', 'on', 'toggle'], 'type': 'LightActuator',
'sequence
Number': 3}, {'id': 'xCo:4693570_u0', 'unit': '', 'name': 'Iluminat Intrare
Usa
', 'value': 'OFF', 'display': True, 'operations': ['off', 'on', 'toggle'],
'type
': 'LightActuator', 'sequenceNumber': 4}, {'id': 'xCo:4777593_u0', 'unit':
'', '
name': 'Iluminat polata fata  ', 'value': 'ON', 'display': True,
'operations': [
'off', 'on', 'toggle'], 'type': 'LightActuator', 'sequenceNumber': 5},
{'id': 'x
Co:4727343_u0', 'unit': '°C', 'name': 'Temperatura Exterioara', 'value':
'12.3',
 'display': True, 'operations': ['history'], 'type':
'OutdoorTemperatureSensor',
 'sequenceNumber': 7}, {'id': 'xCo:4727343_u1', 'unit': ' ', 'name':
'Umiditate
Exterioara', 'value': '100', 'display': True, 'operations': ['history'],
'type':
 'HumiditySensor', 'sequenceNumber': 8}, {'id': 'xCo:4540374_u0', 'unit':
'', 'n
ame': 'Vant', 'value': 'OFF', 'display': True, 'type': 'BinaryInput',
'sequenceN
umber': 9}, {'id': 'xCo:4540374_u1', 'unit': '', 'name': 'Ploaie', 'value':
'OFF
', 'display': True, 'type': 'BinaryInput', 'sequenceNumber': 10}, {'id':
'xCo:40
37170_u0', 'unit': ' ', 'name': 'Bright Ext', 'value': '3', 'display':
True, 'op
erations': ['history'], 'type': 'LuxSensor', 'sequenceNumber': 12}, {'id':
'xCo:
4559319_u0', 'unit': '', 'name': 'Girofar ', 'value': 'OFF', 'display':
True, 'o
perations': ['off', 'on', 'toggle'], 'type': 'SwitchActuator',
'sequenceNumber':
 13}, {'id': 'xCo:4559316_u0', 'unit': '', 'name': 'Sirena ', 'value':
'OFF', 'd
isplay': True, 'operations': ['off', 'on', 'toggle'], 'type':
'SwitchActuator',
'sequenceNumber': 14}, {'id': 'xCo:4628081_u0', 'unit': '', 'name':
'Iluminat te
rasa ', 'value': 'OFF', 'operations': ['off', 'on', 'toggle'], 'type':
'LightAct
uator'}], 'jsonrpc': '2.0'}
2021-01-03 20:54:37,877 DEBUG: Load device for zone "hz_camera_overview"
param:
{'virtual': True, 'zoneName': 'Camera Overview', 'zoneId':
'hz_camera_overview'}

2021-01-03 20:54:37,927 DEBUG: http://192.168.1.3:80 "POST /remote/json-rpc
HTTP
/1.1" 200 None
2021-01-03 20:54:38,127 DEBUG: Response: {'id': 13, 'jsonrpc': '2.0'}
2021-01-03 20:54:38,252 DEBUG: http://192.168.1.3:80 "POST /remote/json-rpc
HTTP
/1.1" 200 None
2021-01-03 20:54:38,452 DEBUG: Response: {'id': 14, 'result': [{'id':
'xCo:44240
13_u0', 'unit': '%', 'name': 'Spot Living ', 'value': '0', 'operations':
['value
'], 'type': 'DimActuator'}, {'id': 'xCo:4422775_u0', 'unit': '', 'name':
'Lustra
 Living ', 'value': 'OFF', 'operations': ['off', 'on', 'toggle'], 'type':
'Light
Actuator'}, {'id': 'xCo:4910835_u0', 'unit': '', 'name': 'Rulou Usa Terasa
', 'v
alue': 'CLOSED', 'operations': ['open', 'close', 'stop', 'stepOpen',
'stepClose'
], 'type': 'ShutterActuator'}, {'id': 'xCo:4910865_u0', 'unit': '', 'name':
'Rul
ou Geam Living ', 'value': 'CLOSED', 'operations': ['open', 'close',
'stop', 'st
epOpen', 'stepClose'], 'type': 'ShutterActuator'}, {'id': 'xCo:4067884_u1',
'uni
t': '%', 'name': 'Air Quality', 'value': '96', 'operations': ['history'],
'type'
: 'AirQualitySensor'}, {'id': 'xCo:4949156_u1', 'unit': '', 'name': 'Usa
Living'
, 'value': 'CLOSED', 'type': 'BinaryDoorSensor'}, {'id': 'xCo:4949156_u0',
'unit
': '', 'name': 'Geam Living', 'value': 'CLOSED', 'type':
'BinaryWindowSensor'},
{'id': 'xCo:4772291_u0', 'unit': '°C', 'name': 'Temperatura Living P1',
'value':
 '24.2', 'operations': ['history'], 'type': 'TemperatureSensor'}, {'id':
'xCo:47
72291_u1', 'unit': '°C', 'name': 'Temperatura Living P2', 'value': '25.3',
'oper
ations': ['history'], 'type': 'TemperatureSensor'}], 'jsonrpc': '2.0'}
could not convert string to float: 'CLOSED'
Traceback (most recent call last):
  File "C:\msys64\mingw32\lib\python3.8\runpy.py", line 194, in
_run_module_as_m
ain
    return _run_code(code, main_globals, None,
  File "C:\msys64\mingw32\lib\python3.8\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\msys64\mingw32\bin\xComfortMQTT.exe\__main__.py", line 7, in
<module>

  File
"C:\msys64\mingw32\lib\python3.8\site-packages\xComfortMQTT\__init__.py",
 line 38, in main
    raise e
  File
"C:\msys64\mingw32\lib\python3.8\site-packages\xComfortMQTT\__init__.py",
 line 32, in main
    cli()
  File "C:\msys64\mingw32\lib\python3.8\site-packages\click\core.py", line
829,
in __call__
    return self.main(*args, **kwargs)
  File "C:\msys64\mingw32\lib\python3.8\site-packages\click\core.py", line
782,
in main
    rv = self.invoke(ctx)
  File "C:\msys64\mingw32\lib\python3.8\site-packages\click\core.py", line
1066,
 in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\msys64\mingw32\lib\python3.8\site-packages\click\core.py", line
610,
in invoke
    return callback(*args, **kwargs)
  File
"C:\msys64\mingw32\lib\python3.8\site-packages\xComfortMQTT\__init__.py",
 line 22, in cli
    service.start()
  File
"C:\msys64\mingw32\lib\python3.8\site-packages\xComfortMQTT\xComforMqtt.p
y", line 136, in start
    self._update()
  File
"C:\msys64\mingw32\lib\python3.8\site-packages\xComfortMQTT\xComforMqtt.p
y", line 151, in _update
    udevice['value'] = float(udevice['value'])
ValueError: could not convert string to float: 'CLOSED'

**Comment by blavka** [comment]
I have not implemented this actor at home, so I will fix it
